---
abstract: 'Web::API - A Simple base module to implement almost every RESTful API with just a few lines of configuration'
author:
  - 'Tobias Kirschstein <lev@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Web-API
requires:
  Carp: '0'
  Data::Dump: '0'
  Data::Random: '0'
  HTTP::Cookies: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Mouse::Role: '0'
  Net::OAuth: '0'
  Time::HiRes: '0'
  URI: '0'
  URI::Escape::XS: '0'
  URI::QueryParam: '0'
  XML::Simple: '0'
  experimental: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/nupfel/Web-API/issues
  homepage: https://github.com/nupfel/Web-API/wiki
  repository: git://github.com/nupfel/Web-API.git
version: '2.2'
